### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by DougMaier** [DougMaier/codelab-js-functions-strings-variables#1]
Hey @icy-wolf, can you take a look at this? It's [hosted here](http://aberrant-bread.surge.sh) and meets the following [project](http://lansingcodelab.com/lessons/js-functions-strings-variables/1) criteria:
- [x] an HTML profile with a name, favorite color, and at least one other attribute
- [x] the containing element for each attribute is blank initially
- [x] prompts are used to collect text values for each attribute
- [x] each attribute is given an `id` (e.g. "name", "favorite-color"), which is used to target that element (with [`document.getElementById`](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById)) and set its [`innerHTML`](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML) to the value provided by the user

It's short on style, but functional.

**Comment by icy-wolf** [comment]
:shipit:
